# Generated by Django 4.2.23 on 2025-08-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, unique=True)),
                ('born_date', models.CharField(max_length=50)),
                ('born_location', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
