# Generated by Django 4.2.23 on 2025-08-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
